appcompany/appcompany/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
	path('', include('founds.urls') ),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='login/')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appcompany/founds/urls.py
from django.urls import path
from . import views as found_views

app_name = 'founds' 


urlpatterns = [
    path('login/',  found_views.user_login, name='user_login'),
    path('logout/',  found_views.user_logout, name='user_logout'),
    path('register', found_views.register, name='register'),
    path('borrower/<int:u_id>/', found_views.borrower, name='borrower'),
    path('lender/<int:u_id>/', found_views.lender, name='lender'),
   # path('loan/', found_views.loan, name='loan')
 ]

appcompany/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Founds application{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">  

</head>
<body>
    <main>
    <!-- header code -->
    {% block content %}
    {% endblock %}
    <!-- footer code -->
    </main>
    <footer class="footer text-center" style="font-size: 11px;">
      <span class="text-muted">@ Desarrollado por Karina Jimenes.</span>
    </footer>
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

appcompany/templates/borrower.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
	{% include "logout.html" %}
	<div class="row">
		<div class="col">
			<p><strong>Name </strong>{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</p>
  			<hr class="m-1">
  			<p><strong>Amount Needed: </strong> $ {{ user.borrower.amount_needed}} </p>
  			<hr class="m-1">
  			<p><strong>Amount Raised: </strong>$ {{ user.borrower.amount_raised}}</p>
  			<hr class="m-1">
  			<div class="col py-3">
  				<h6>List of people who lent you money</h6>
  			</div>
                {% if messages %}
                    {% for message in messages %}
                            <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
			<div class="table-responsive">
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th>Name</th>
							<th>Email</th>
							<th>Ammount Lent</th>
						</tr>
					</thead>
					<tbody>
                        {% for loan in lst_lender_loans %}
						<tr>
							<td>{{ loan.lender_user.user.first_name }} {{ loan.lender_user.user.last_name }}</td>
							<td>{{ loan.lender_user.user.email }} </td>
							<td>$ {{ loan.amount_lend }}</td>
						</tr>
                        {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

appcompany/templates/lender.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
	{% include "logout.html" %}
	<div class="row">
		<div class="col">
			<p><strong>Name: </strong>{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</p>
  			<hr class="m-1">
  			<p><strong>Amount Balance: </strong> $ {{ user.lender.money }}</p>
  			<hr class="m-1">
  			<div class="col py-3">
  				<h6>List of people who are in need of help</h6>
  			</div>
                {% if messages %}
                    {% for message in messages %}
                            <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
			<div class="table-responsive">
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th>Name</th>
							<th>Money needed for</th>
							<th>Description</th>
							<th>Amount needed</th>
							<th>Amount raised</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						{% for borrower in lst_borrowers %}
						<tr>
							<td>{{ borrower.user.first_name }} {{ borrower.user.last_name }}</td>
							<td>{{ borrower.need_money_for }}</td>
							<td>{{ borrower.description }}</td>
							<td>$ {{ borrower.amount_needed }}</td>
							<td>$ {{ borrower.amount_raised }}</td>
							<td>
								<form  method="POST" class="form-inline">
									{% csrf_token %}
									<input type="hidden" name="user_lender" value="{{ user.lender.id }}">
									<input type="hidden" name="user_borrower" value="{{ borrower.id }}">
									<div class="form-group">
										<input type="number" class="form-control form-control-sm" name="ammount">
									</div>
    								<button class="btn btn-sm btn-info " aria-label="sign in button" type="submit">Lend</button>
								</form>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="col py-3">
				<h6>List of people you lent money to</h6>
			</div>
			<div class="table-responsive">
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th>Name</th>
							<th>Money needed for</th>
							<th>Description</th>
							<th>Amount needed</th>
							<th>Amount raised</th>
							<th>Amount lend</th>
						</tr>
					</thead>
					<tbody>
						{% for loan in lst_lender_loans %}
						<tr>
							<td>{{ loan.borrower_user.user.first_name }} {{ loan.borrower_user.user.last_name }}</td>
							<td>{{ loan.borrower_user.need_money_for }}</td>
							<td>{{ loan.borrower_user.description }}</td>
							<td>$ {{ loan.borrower_user.amount_needed }}</td>
							<td>$ {{ loan.borrower_user.amount_raised }}</td>
							<td>$ {{ loan.amount_lend }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

appcompany/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="row">
    	<div class="col-md-6">
            <div class="py-3">
                <h1 class="h3 mb-3 font-weight-normal">Login</h1>
            </div>
    		
    		<form method="POST" class="p-4">
    			{% csrf_token %}
    			<div class="form-group row">
    				{{ form.email.label_tag }}
                    <div class="col-sm-10">
    				{{ form.email }}
                    </div>
    			</div>
    			<div class="form-group row">
    				{{ form.password.label_tag }}
                    <div class="col-sm-10">
    				{{ form.password }}
                    </div>
    			</div>
    			<div class="row pt-4">
    				<div class="col">
    					<a class="nav-link"  href="{% url 'founds:register' %}">Click here to register?</a>
    				</div>
    				<div class="col">
    					<button class="btn btn-sm btn-block btn-info " aria-label="sign in button" type="submit">Login</button>
    				</div>
    			</div>
    			
                {% if messages %}
                    {% for message in messages %}
                            <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
    		</form> 
    	</div>
	</div>
</div>
{% endblock %}

appcompany/templates/logout.html
<header>
    <div class="d-flex bd-highlight mb-3">
     <div class="ml-auto p-2 bd-highlight"><a class="nav-link" href="{% url 'founds:user_logout' %}">Logout</a></div>
    </div>
</header>

appcompany/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col">
            <div class="py-3">
                <h2 class="h3 mb-3 font-weight-normal">Lender</h2>
            </div>
			<form method="POST" class="p-2" id="lender_form">
                {% csrf_token %}
                <div class="form-group row">
                    {{ lender_form.first_name.label_tag }}
                    <div class="col-sm-8">
                    {{ lender_form.first_name }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ lender_form.last_name.label_tag }}
                    <div class="col-sm-8">
                    {{ lender_form.last_name }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ lender_form.email.label_tag }}
                    <div class="col-sm-8">
                    {{ lender_form.email }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ lender_form.password.label_tag }}
                    <div class="col-sm-8">
                    {{ lender_form.password }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ lender_form.money.label_tag }}
                    <div class="col-sm-8">
                    {{ lender_form.money }}
                    </div>
                </div>
    			<div class="row pt-4">
                    <input type="hidden" name="form_type" value="lender_form">
    				<div class="col">
    					<a class="nav-link" href="{% url 'founds:user_login' %}" >Already a member?</a>
    				</div>
    				<div class="col">
    					<button class="btn btn-sm btn-block btn-info " aria-label="sign in button" type="submit">Register</button>
    				</div>
    			</div>
    		</form>
		</div>
		<div class="col">
            <div class="py-3">
                <h2 class="h3 mb-3 font-weight-normal">Borrower</h2>
            </div>
			<form method="POST" class="p-2" id="borrower_form">
                {% csrf_token %}
                <div class="form-group row">
                    {{ borrower_form.bfirst_name.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.bfirst_name }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ borrower_form.blast_name.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.blast_name }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ borrower_form.bemail.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.bemail }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ borrower_form.bpassword.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.bpassword }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ borrower_form.bneed_money_for.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.bneed_money_for }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ borrower_form.bdescription.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.bdescription }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ borrower_form.bamount_needed.label_tag }}
                    <div class="col-sm-8">
                    {{ borrower_form.bamount_needed }}
                    </div>
                </div>
    			<div class="row pt-4">
                    <input type="hidden" name="form_type" value="borrower_form">
    				<div class="col">
    					<a class="nav-link" href="{% url 'founds:user_login' %}">Already a member?</a>
    				</div>
    				<div class="col">
    					<button class="btn btn-sm btn-block btn-info " aria-label="sign in button" type="submit">Register</button>
    				</div>
    			</div>
    		
    		</form>
		</div>
	</div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}